<?php

declare(strict_types=1);

namespace App\Http\OpenApi;

/**
 * Tenant API path definitions. Base path /api. Call from tenant domain.
 *
 * @SWG\Path(path="/v1/catalog/products", get=@SWG\Get(tags={"Tenant - Catalog"}, summary="List products", description="Public. Tenant domain.", @SWG\Response(response=200, description="List of products")))
 * @SWG\Path(path="/v1/catalog/products/{id}", get=@SWG\Get(tags={"Tenant - Catalog"}, summary="Get product", @SWG\Parameter(in="path", name="id", type="string", required=true), @SWG\Response(response=200, description="Product"), @SWG\Response(response=404, description="Not found")))
 * @SWG\Path(path="/v1/catalog/products", post=@SWG\Post(tags={"Tenant - Catalog"}, summary="Create product", security={{"bearerAuth":{}}}, @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"name","slug","price_minor_units","currency"}, @SWG\Property(property="name", type="string"), @SWG\Property(property="slug", type="string"), @SWG\Property(property="description", type="string"), @SWG\Property(property="price_minor_units", type="integer"), @SWG\Property(property="currency", type="string"))), @SWG\Response(response=200, description="Created product"), @SWG\Response(response=403, description="Forbidden"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/catalog/products/{id}/price", patch=@SWG\Patch(tags={"Tenant - Catalog"}, summary="Update product price", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="id", type="string", required=true), @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"price_minor_units","currency"}, @SWG\Property(property="price_minor_units", type="integer"), @SWG\Property(property="currency", type="string"))), @SWG\Response(response=200, description="Updated"), @SWG\Response(response=404, description="Not found")))
 * @SWG\Path(path="/v1/catalog/products/{id}/activate", post=@SWG\Post(tags={"Tenant - Catalog"}, summary="Activate product", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="id", type="string", required=true), @SWG\Response(response=200, description="Activated"), @SWG\Response(response=404, description="Not found")))
 * @SWG\Path(path="/v1/catalog/products/{id}/deactivate", post=@SWG\Post(tags={"Tenant - Catalog"}, summary="Deactivate product", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="id", type="string", required=true), @SWG\Response(response=200, description="Deactivated"), @SWG\Response(response=404, description="Not found")))
 * @SWG\Path(path="/v1/cart", post=@SWG\Post(tags={"Tenant - Cart"}, summary="Create cart", security={{"bearerAuth":{}}}, @SWG\Parameter(in="body", name="body", @SWG\Schema(type="object", @SWG\Property(property="customer_email", type="string"), @SWG\Property(property="session_id", type="string"))), @SWG\Response(response=201, description="Cart created"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/cart/{cartId}", get=@SWG\Get(tags={"Tenant - Cart"}, summary="Get cart", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="cartId", type="string", required=true), @SWG\Response(response=200, description="Cart"), @SWG\Response(response=404, description="Not found")))
 * @SWG\Path(path="/v1/cart/{cartId}/items", post=@SWG\Post(tags={"Tenant - Cart"}, summary="Add item to cart", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="cartId", type="string", required=true), @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"product_id","quantity","unit_price_minor_units","currency"}, @SWG\Property(property="product_id", type="string", format="uuid"), @SWG\Property(property="quantity", type="integer"), @SWG\Property(property="unit_price_minor_units", type="integer"), @SWG\Property(property="currency", type="string"))), @SWG\Response(response=200, description="Item added"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/cart/{cartId}/items/{productId}", put=@SWG\Put(tags={"Tenant - Cart"}, summary="Update cart item", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="cartId", type="string", required=true), @SWG\Parameter(in="path", name="productId", type="string", required=true), @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"quantity"}, @SWG\Property(property="quantity", type="integer"))), @SWG\Response(response=200, description="Item updated"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/cart/{cartId}/items/{productId}", delete=@SWG\Delete(tags={"Tenant - Cart"}, summary="Remove item from cart", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="cartId", type="string", required=true), @SWG\Parameter(in="path", name="productId", type="string", required=true), @SWG\Response(response=200, description="Item removed")))
 * @SWG\Path(path="/v1/cart/{cartId}/clear", post=@SWG\Post(tags={"Tenant - Cart"}, summary="Clear cart", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="cartId", type="string", required=true), @SWG\Response(response=200, description="Cart cleared")))
 * @SWG\Path(path="/v1/cart/{cartId}/convert", post=@SWG\Post(tags={"Tenant - Cart"}, summary="Convert cart to order", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="cartId", type="string", required=true), @SWG\Response(response=200, description="Order created"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/cart/{cartId}/abandon", post=@SWG\Post(tags={"Tenant - Cart"}, summary="Abandon cart", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="cartId", type="string", required=true), @SWG\Response(response=200, description="Cart abandoned")))
 * @SWG\Path(path="/v1/checkout", post=@SWG\Post(tags={"Tenant - Checkout"}, summary="Checkout cart", security={{"bearerAuth":{}}}, @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"cart_id","payment_provider","customer_email"}, @SWG\Property(property="cart_id", type="string", format="uuid"), @SWG\Property(property="payment_provider", type="string", enum={"stripe","manual","paypal"}), @SWG\Property(property="customer_email", type="string", format="email"), @SWG\Property(property="coupon_codes", type="array", items=@SWG\Items(type="string"))), @SWG\Response(response=200, description="Order and payment created; returns client_secret for Stripe"), @SWG\Response(response=400, description="Bad request"), @SWG\Response(response=422, description="Empty cart or stock validation")))
 * @SWG\Path(path="/v1/checkout/confirm-payment", post=@SWG\Post(tags={"Tenant - Checkout"}, summary="Confirm checkout payment", security={{"bearerAuth":{}}}, @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"payment_id"}, @SWG\Property(property="payment_id", type="string", format="uuid"), @SWG\Property(property="provider_payment_id", type="string"))), @SWG\Response(response=200, description="Payment confirmed"), @SWG\Response(response=400, description="Bad request")))
 * @SWG\Path(path="/v1/orders", post=@SWG\Post(tags={"Tenant - Orders"}, summary="Create order", security={{"bearerAuth":{}}}, @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"customer_email"}, @SWG\Property(property="customer_email", type="string", format="email"))), @SWG\Response(response=201, description="Order created"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/orders/{orderId}", get=@SWG\Get(tags={"Tenant - Orders"}, summary="Get order", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="orderId", type="string", required=true), @SWG\Response(response=200, description="Order"), @SWG\Response(response=404, description="Not found")))
 * @SWG\Path(path="/v1/orders/{orderId}/items", post=@SWG\Post(tags={"Tenant - Orders"}, summary="Add order item", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="orderId", type="string", required=true), @SWG\Parameter(in="body", name="body", required=true), @SWG\Response(response=200, description="Item added"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/orders/{orderId}/confirm", post=@SWG\Post(tags={"Tenant - Orders"}, summary="Confirm order", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="orderId", type="string", required=true), @SWG\Response(response=200, description="Order confirmed")))
 * @SWG\Path(path="/v1/orders/{orderId}/pay", post=@SWG\Post(tags={"Tenant - Orders"}, summary="Mark order paid", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="orderId", type="string", required=true), @SWG\Response(response=200, description="Order paid")))
 * @SWG\Path(path="/v1/orders/{orderId}/ship", post=@SWG\Post(tags={"Tenant - Orders"}, summary="Ship order", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="orderId", type="string", required=true), @SWG\Response(response=200, description="Order shipped")))
 * @SWG\Path(path="/v1/orders/{orderId}/cancel", post=@SWG\Post(tags={"Tenant - Orders"}, summary="Cancel order", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="orderId", type="string", required=true), @SWG\Response(response=200, description="Order cancelled")))
 * @SWG\Path(path="/v1/payments", post=@SWG\Post(tags={"Tenant - Payments"}, summary="Create payment", security={{"bearerAuth":{}}}, @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"order_id","amount_minor_units","currency","provider"}, @SWG\Property(property="order_id", type="string", format="uuid"), @SWG\Property(property="amount_minor_units", type="integer"), @SWG\Property(property="currency", type="string"), @SWG\Property(property="provider", type="string", enum={"stripe","manual","paypal"}))), @SWG\Response(response=201, description="Payment created; returns client_secret for Stripe"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/payments/order/{orderId}", get=@SWG\Get(tags={"Tenant - Payments"}, summary="List payments for order", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="orderId", type="string", required=true), @SWG\Response(response=200, description="List of payments")))
 * @SWG\Path(path="/v1/payments/{paymentId}/confirm", post=@SWG\Post(tags={"Tenant - Payments"}, summary="Confirm payment", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="paymentId", type="string", required=true), @SWG\Parameter(in="body", name="body", @SWG\Schema(type="object", @SWG\Property(property="provider_payment_id", type="string"))), @SWG\Response(response=200, description="Payment confirmed"), @SWG\Response(response=400, description="Bad request")))
 * @SWG\Path(path="/v1/payments/{paymentId}/refund", post=@SWG\Post(tags={"Tenant - Payments"}, summary="Refund payment", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="paymentId", type="string", required=true), @SWG\Response(response=200, description="Refund initiated")))
 * @SWG\Path(path="/v1/payments/{paymentId}/cancel", post=@SWG\Post(tags={"Tenant - Payments"}, summary="Cancel payment", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="paymentId", type="string", required=true), @SWG\Response(response=200, description="Payment cancelled")))
 * @SWG\Path(path="/v1/inventory", post=@SWG\Post(tags={"Tenant - Inventory"}, summary="Create stock", security={{"bearerAuth":{}}}, @SWG\Parameter(in="body", name="body", required=true), @SWG\Response(response=201, description="Stock created"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/inventory/{productId}", get=@SWG\Get(tags={"Tenant - Inventory"}, summary="Get stock for product", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="productId", type="string", required=true), @SWG\Response(response=200, description="Stock"), @SWG\Response(response=404, description="Not found")))
 * @SWG\Path(path="/v1/inventory/{productId}/increase", post=@SWG\Post(tags={"Tenant - Inventory"}, summary="Increase stock", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="productId", type="string", required=true), @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"quantity"}, @SWG\Property(property="quantity", type="integer"))), @SWG\Response(response=200, description="Stock increased")))
 * @SWG\Path(path="/v1/inventory/{productId}/decrease", post=@SWG\Post(tags={"Tenant - Inventory"}, summary="Decrease stock", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="productId", type="string", required=true), @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"quantity"}, @SWG\Property(property="quantity", type="integer"))), @SWG\Response(response=200, description="Stock decreased")))
 * @SWG\Path(path="/v1/inventory/{productId}/reserve", post=@SWG\Post(tags={"Tenant - Inventory"}, summary="Reserve stock", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="productId", type="string", required=true), @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"quantity"}, @SWG\Property(property="quantity", type="integer"))), @SWG\Response(response=200, description="Stock reserved")))
 * @SWG\Path(path="/v1/inventory/{productId}/release", post=@SWG\Post(tags={"Tenant - Inventory"}, summary="Release stock", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="productId", type="string", required=true), @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"quantity"}, @SWG\Property(property="quantity", type="integer"))), @SWG\Response(response=200, description="Stock released")))
 * @SWG\Path(path="/v1/inventory/{productId}/threshold", patch=@SWG\Patch(tags={"Tenant - Inventory"}, summary="Set low stock threshold", security={{"bearerAuth":{}}}, @SWG\Parameter(in="path", name="productId", type="string", required=true), @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"threshold"}, @SWG\Property(property="threshold", type="integer"))), @SWG\Response(response=200, description="Threshold set")))
 * @SWG\Path(path="/v1/customer/register", post=@SWG\Post(tags={"Tenant - Customer"}, summary="Register customer", description="Public. Tenant domain.", @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"email","password","first_name","last_name"}, @SWG\Property(property="email", type="string"), @SWG\Property(property="password", type="string"), @SWG\Property(property="first_name", type="string"), @SWG\Property(property="last_name", type="string"), @SWG\Property(property="phone", type="string"))), @SWG\Response(response=201, description="Registered; returns token"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/customer/login", post=@SWG\Post(tags={"Tenant - Customer"}, summary="Login customer", @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"email","password"}, @SWG\Property(property="email", type="string"), @SWG\Property(property="password", type="string"))), @SWG\Response(response=200, description="Returns token"), @SWG\Response(response=422, description="Invalid credentials")))
 * @SWG\Path(path="/v1/customer/forgot-password", post=@SWG\Post(tags={"Tenant - Customer"}, summary="Forgot password", @SWG\Parameter(in="body", name="body", required=true, @SWG\Schema(type="object", required={"email"}, @SWG\Property(property="email", type="string"))), @SWG\Response(response=200, description="Reset link sent")))
 * @SWG\Path(path="/v1/customer/reset-password", post=@SWG\Post(tags={"Tenant - Customer"}, summary="Reset password", @SWG\Parameter(in="body", name="body", required=true), @SWG\Response(response=200, description="Password reset"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/customer/logout", post=@SWG\Post(tags={"Tenant - Customer"}, summary="Logout customer", security={{"customerAuth":{}}}, @SWG\Response(response=200, description="Logged out")))
 * @SWG\Path(path="/v1/customer/me", get=@SWG\Get(tags={"Tenant - Customer"}, summary="Get current customer", security={{"customerAuth":{}}}, @SWG\Response(response=200, description="Customer profile"), @SWG\Response(response=401, description="Unauthorized")))
 * @SWG\Path(path="/v1/customer/profile", patch=@SWG\Patch(tags={"Tenant - Customer"}, summary="Update profile", security={{"customerAuth":{}}}, @SWG\Parameter(in="body", name="body", required=true), @SWG\Response(response=200, description="Profile updated"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/customer/addresses", get=@SWG\Get(tags={"Tenant - Customer"}, summary="List addresses", security={{"customerAuth":{}}}, @SWG\Response(response=200, description="List of addresses")))
 * @SWG\Path(path="/v1/customer/addresses", post=@SWG\Post(tags={"Tenant - Customer"}, summary="Add address", security={{"customerAuth":{}}}, @SWG\Parameter(in="body", name="body", required=true), @SWG\Response(response=201, description="Address created"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/customer/addresses/{id}", patch=@SWG\Patch(tags={"Tenant - Customer"}, summary="Update address", security={{"customerAuth":{}}}, @SWG\Parameter(in="path", name="id", type="string", required=true), @SWG\Parameter(in="body", name="body", required=true), @SWG\Response(response=200, description="Address updated"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/customer/addresses/{id}", delete=@SWG\Delete(tags={"Tenant - Customer"}, summary="Delete address", security={{"customerAuth":{}}}, @SWG\Parameter(in="path", name="id", type="string", required=true), @SWG\Response(response=200, description="Address deleted")))
 * @SWG\Path(path="/v1/customer/password/change", post=@SWG\Post(tags={"Tenant - Customer"}, summary="Change password", security={{"customerAuth":{}}}, @SWG\Parameter(in="body", name="body", required=true), @SWG\Response(response=200, description="Password changed"), @SWG\Response(response=422, description="Validation error")))
 * @SWG\Path(path="/v1/customer/export", get=@SWG\Get(tags={"Tenant - Customer"}, summary="Export data (GDPR)", security={{"customerAuth":{}}}, @SWG\Response(response=200, description="Export data")))
 * @SWG\Path(path="/v1/customer/account", delete=@SWG\Delete(tags={"Tenant - Customer"}, summary="Delete account", security={{"customerAuth":{}}}, @SWG\Response(response=200, description="Account deleted")))
 * @SWG\Path(path="/v1/reports/revenue", get=@SWG\Get(tags={"Tenant - Reports"}, summary="Revenue report", security={{"bearerAuth":{}}}, @SWG\Response(response=200, description="Revenue data")))
 * @SWG\Path(path="/v1/reports/tax", get=@SWG\Get(tags={"Tenant - Reports"}, summary="Tax report", security={{"bearerAuth":{}}}, @SWG\Response(response=200, description="Tax data")))
 * @SWG\Path(path="/v1/reports/products", get=@SWG\Get(tags={"Tenant - Reports"}, summary="Products report", security={{"bearerAuth":{}}}, @SWG\Response(response=200, description="Products report")))
 * @SWG\Path(path="/v1/reports/conversion", get=@SWG\Get(tags={"Tenant - Reports"}, summary="Conversion report", security={{"bearerAuth":{}}}, @SWG\Response(response=200, description="Conversion data")))
 */
class ApiPathsTenant
{
}
